/** PR-4 UI strings — move to i18n keys when PR-2b lands. */

export const deadSymbolStrings = {
  panelTitle: "Dead Symbols",
  ignoreListTitle: "Ignore List",
  healthTab: "Project Health",
  deadTab: "Dead Symbols",
  ignoreTab: "Ignore List",
  searchPlaceholder: "Search name, file, kind…",
  kindAll: "All kinds",
  kindUnused: "unused",
  kindBroken: "broken",
  sortName: "Name",
  sortFile: "File",
  sortKind: "Kind",
  total: (n: number) => `${n} total`,
  noSymbols: "No dead symbols in the index.",
  noIgnored: "No ignored symbols.",
  selectSymbol: "Select a symbol to view details.",
  lastRef: "last_ref",
  noLastRef: "referans yok",
  project: "Project",
  fileLine: "File",
  detail: "Detail",
  openInEditor: "Open in Editor",
  copyPath: "Copy path",
  ignore: "Ignore",
  unignore: "Unignore",
  fixWithAgent: "Fix with agent",
  taskQueued: (msg: string) => `Task queued: ${msg}`,
  noAgent: "No agent available — connect a worker in Fleet.",
  viewAll: (n: number) => `View all ${n}`,
  reindex: "Re-index workspace",
  deadDrillDown: (n: number) => `${n} dead symbols`,
} as const;
