/** PR-3 vault UI strings — move to i18n keys when PR-2b lands. */
export const vaultStrings = {
  experienceLog: "Experience Log",
  semanticMapTitle: "SEMANTIC MAP + EXPERIENCES",
  deadSymbols: "Dead Symbols",
  clean: "temiz",
  warnings: (n: number) => `${n} uyarı`,
  noDeadForNode: (name: string) => `Bu düğüm için dead symbol yok · ${name}`,
  noExperiencesForNode: (name: string) => `Bu düğüm için experience yok · ${name}`,
  noExperiences: "Experience kaydı yok",
  showArchived: "Show Archived",
  hideArchived: "Hide Archived",
  archivedLabel: "archived",
  unreviewed: "unreviewed",
  markReviewed: "Mark reviewed",
  markAllReviewed: "Mark all reviewed",
  edit: "Edit",
  save: "Save",
  cancel: "Cancel",
  archive: "Archive",
  unarchive: "Restore",
  pin: "Pin",
  unpin: "Unpin",
  restoreTtl: "Restore from auto-archive",
  loading: "Loading…",
  loadError: "Could not load experience details.",
  archiveConfirm: "Archive this experience? It can be restored from Show Archived.",
  originalContent: "Original content",
  metadata: "Metadata",
  useCount: "Use count",
  lastUsed: "Last used",
  updated: "Updated",
  source: "Source",
  relatedTask: "Related task",
  tags: "Tags",
  outcome: "Outcome",
  project: "Project",
  agent: "Agent",
  adr: "ADR / Summary",
  pathReference: "Path reference",
  totalExperiences: (n: number) => `${n} experiences`,
  astNodes: (n: number) => `${n} AST nodes`,
  edges: (n: number) => `${n} edges`,
  files: (n: number) => `${n} files`,
  useful: "Faydalı",
  usefulDone: "Faydalı ✓",
  whisper: "WHISPER",
  synced: "Synced",
  filter: (name: string) => `filter · ${name}`,
  whisperLive: (n: number) => `fısıltı · ${n}`,
} as const;
